### ISSUE TITLE
请问能否提供数据

### ISSUE THREAD

**Issue by zhiaozhou** [caichongchao/weibo_stock_data#1]
您好，
我是来自纽约大学的研究所，现在正在做微博舆情预测股价的研究，请问能否分享您的数据，非常感谢！

**Comment by wasdfghjklr** [comment]
您好，我是来自天津大学的硕士研究生。
请问您拿到微博舆情的数据了么？可以分享一下么？谢谢!

**Comment by caichongchao** [comment]
用处不大，结果不是很好，你有兴趣可以做做股吧的分析，不过也很差。




在 2019-11-13 19:22:53，"wasdfghjklr" <notifications@github.com> 写道：


您好，我是来自天津大学的硕士研究生。
请问您拿到微博舆情的数据了么？可以分享一下么？谢谢!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易163邮箱发来的云附件
微博数据集.rar (36.22M, 2019年11月30日 9:13 到期)
下载
